FROM node:16-alpine

WORKDIR /usr/crowd/frontend

COPY package-lock.json package.json ./
RUN npm ci

COPY .browserslistrc .eslintrc.cjs .prettierrc babel.config.js postcss.config.js tailwind.config.cjs vue.config.js ./
COPY ./public ./public
COPY ./src ./src